### ISSUE TITLE
Authors empty field in pdf output with quarto 1.3.*

### ISSUE THREAD

**Issue by fradav** [kapsner/authors-block#5] opened 2023-04-04 12:52 UTC
It leaves blank spaces instead of authors names in pdf/latex output.

workaround: revert to quarto 1.2.

**Comment by kapsner** [comment] 2023-04-04 16:20
Thanks for this bug report - I will have a look at it soon.

**Comment by kapsner** [comment] 2023-04-04 18:44
Hi @fradav , I was able to reproduce the issue running quarto v 1.3.306 inside a Ubtuntu 22.04 Docker container. Rendering docx, everything seems fine.

The main intention of this extension was to provide a tool especially for the output format `docx` as other extensions already exist that provide author blocks for PDF documents.

Unfortunately, I currently cannot put much efforts into debugging this issue, which I assume is like related to latex, as I am very limited in time at the moment an my main focus is to provide a working version for docx format.

But contributions / PRs are very welcome 😉

**Comment by kapsner** [comment] 2023-04-04 20:18
@fradav I might have found the issue and have just worked on a fix. Please test the updated version with `quarto add kapsner/authors-block@development`.

**Comment by fradav** [comment] 2023-04-05 00:47
Thanks you very much it works now!

**Comment by kapsner** [comment] 2023-04-05 15:23
I'll leave this issue open until stable version of RStudio comes with Quarto >=1.3 (currently the use Quarto 1.2.335, https://docs.posit.co/ide/news/#rstudio-2023.03.0).

The issue is now indicated in the [README.md](https://github.com/kapsner/authors-block) and the commit with compatibility for Quarto >=1.3 is now tagged as [`v0.2.0`](https://github.com/kapsner/authors-block/releases/tag/v0.2.0).

To install, simply run `quarto add kapsner/authors-block@v0.2.0`.

**Comment by kapsner** [comment] 2023-05-23 10:16
Closing this as #7 was merged into the main branch

**Closed as completed by kapsner** 2023-05-23 10:16 UTC
Labels: bug
